### ISSUE TITLE
` find_loader` does not exist in Python 3.12 anymore and should be replaced by `exec_module()`

### ISSUE THREAD

**Issue by hugobuddel** [christophercrouzet/gorilla#7]
gorilla does not work with Python 3.12:

```
$ python -m unittest
............................E..
======================================================================
ERROR: test_find_patches_2 (tests.test_utils.UtilsTest.test_find_patches_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/guix-build-python-gorilla-0.4.0.drv-0/source/tests/test_utils.py", line 360, in test_find_patches_2
    patches = gorilla.find_patches([_utils])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/guix-build-python-gorilla-0.4.0.drv-0/source/gorilla.py", line 658, in find_patches
    for module in modules:
                  ^^^^^^^
  File "/tmp/guix-build-python-gorilla-0.4.0.drv-0/source/gorilla.py", line 657, in <genexpr>
    for module in _module_iterator(package, recursive=recursive))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/guix-build-python-gorilla-0.4.0.drv-0/source/gorilla.py", line 859, in _module_iterator
    module = _load_module(finder, module_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/guix-build-python-gorilla-0.4.0.drv-0/source/gorilla.py", line 56, in _load_module
    loader, _ = finder.find_loader(name)
                ^^^^^^^^^^^^^^^^^^
AttributeError: 'FileFinder' object has no attribute 'find_loader'

----------------------------------------------------------------------
Ran 31 tests in 1.975s

FAILED (errors=1)
```

Running it with Python 3.11 gives this warning:
```
>   <frozen importlib._bootstrap>:283: DeprecationWarning: the load_module() method is deprecated and slated for removal in Python 3.12; use exec_module() instead
```

**Comment by christophercrouzet** [comment]
Thanks @hugobuddel, this should be addressed in commit [9402df5](https://github.com/christophercrouzet/gorilla/commit/9402df5bda2d9279f46df3cf29ac86797c893920).

**Comment by hugobuddel** [comment]
Thank you @christophercrouzet !
